### ISSUE TITLE
Option to list url

### ISSUE THREAD

**Issue by smhmd** [KevCui/animepahe-dl#1]
Use case: to pipe them into a file for download or streaming through `mpv` or some other video player.

**Comment by KevCui** [comment]
I see, let me check what I can do for it.

**Comment by KevCui** [comment]
Done, option `-l` will show only video link. In order to pipe it into the media player, better to use `-l` with `-s` and `-e` together for now. Details in commit 784d67b71f2a67f0b60c77d61be4f27748090078
