### ISSUE TITLE
unsupported audio

### ISSUE THREAD

**Issue by Orironer** [KevCui/animepahe-dl#100]
hey so i watch anime in a sony bravia tv so i downoad the anime put it in a pd and watch but lots of things i download from animepahe-dl is having unsupported audio issue not every but most whilst if downloaded for the site directly there is no such issue i use "./animepahe-dl.sh -t 8 -r 720" for downloading any help will be appreciated

**Comment by KevCui** [comment]
Hey @Orironer, I have little to none knowledge about sony bravia tv. I guess it doesn't have certain audio codec? Did you try to install other media player, if installing app is supported, like VLC? If you got the exact error text, then maybe you can search it online and find some solutions, hopefully.

**Comment by Orironer** [comment]
hey thanks for the reply i just wanted to ask like in sometimes the script download audio format of 73kbps bitrate stereo and 24kHz and that works for me but other times it download 47kbps bitrate mono and 22.05kHz that do not work in my tv so is there a way to sett this audio format appropriately ? even 128kbps bit rate stereo and 44.1kHz works for me and if downloaded in from anime pahe directely it always gives the 73bitrate which works

**Comment by KevCui** [comment]
Hey @Orironer, the bitrate you mentioned sometimes works is not controlled/set in the script. It depends on the video source I think. The script downloads the video which is used for streaming from aminepahe, not the video source downloaded from download button. That is the difference. 

However,  maybe some ffmpeg options can covert bitrate. I'm not deep into ffmpeg or video/audio convert thing, so I'm not exactly sure. If you like, you can modify code in line  https://github.com/KevCui/animepahe-dl/blob/master/animepahe-dl.sh#L364 and try out. Good luck!

**Comment by Orironer** [comment]
thanks id figure something from here btw i just learned that the format i was talking about is called vcodec:h264, res:720, acodec:m4a

**Comment by KevCui** [comment]
Hey @Orironer, hope you found a solution to the problem you were facing. I'm closing this issue because I don't think something will be implemented in this script. Cheers.
