### ISSUE TITLE
[ERROR] jq command not found!

### ISSUE THREAD

**Issue by Kanon-chan** [KevCui/animepahe-dl#101]
![image](https://github.com/KevCui/animepahe-dl/assets/135102703/da91703a-cd48-4368-9194-b4bc76bc0d1b)

![Screenshot 2024-03-10 170838](https://github.com/KevCui/animepahe-dl/assets/135102703/2ab111d6-8444-4ea7-a1d8-540013a98976)
Cant start to download or try downloading 
![image](https://github.com/KevCui/animepahe-dl/assets/135102703/35a24599-7b6a-469a-8077-52c2f1d3ab97)
Ive tried to download jq in powershell numerous times already

**Comment by KevCui** [comment]
Hey @Kanon-chan, it looks like jq is installed in a place where the script cannot find it. You can download executable binary from  https://jqlang.github.io/jq/download/ and place it under `/mingw64/bin/`. I saw from your screenshot curl is under this path as well, and it looks like script can find curl. So, it should work for jq as well.

**Comment by KevCui** [comment]
Hey @Kanon-chan, there is no reply from your side since a month ago. I'd assume you've already solved your issue? Hope so. I'm closing this issue now. Feel free to let me know if you have any trouble. Cheers.
