### ISSUE TITLE
is there a similar repo but for movies and tvshows

### ISSUE THREAD

**Issue by francqz31** [KevCui/animepahe-dl#102]
Hey amazing repo , I use it a lot and like it. But I was wondering if there are similar repos like this amazing repo for movies and Tv shows.
Maybe a repo that supports downloading from https://hurawatch.bz/home  or https://fmoviesz.to/home for example.

Thanks in advance.

edit: or maybe if you can add support for those on animepahe-dl ?

**Comment by KevCui** [comment]
Hey @francqz31, I don't know if similar projects exist or not. Unfortunately, there is no plan to support those sites in this script. Sorry.

**Comment by KevCui** [comment]
@francqz31 If you like, you may check out https://github.com/KevCui/soaper-dl. It is not related to the sites you recommended, however it has TV series and movies you may be interested in.
