### ISSUE TITLE
Missing video list

### ISSUE THREAD

**Issue by marcusbake22** [KevCui/animepahe-dl#103]
![gittt](https://github.com/KevCui/animepahe-dl/assets/156812295/4a1dab62-187e-466a-98f1-3ec5fce9b56f)
Missing video list everytime someone please help

**Comment by KevCui** [comment]
Hey @marcusbake22, which anime are you downloading? If you would like to share the name, I can take a quick look.

**Comment by marcusbake22** [comment]
i was downloading domestic girlfriend and even seven deadly sins but it keeps doing that

**Comment by KevCui** [comment]
Hey @marcusbake22, I checked "Domestic na Kanojo" is downloading for me. May I ask if you are able to watch it on animepahe site from your device? If yes, then please run script with `-d` flag in the end, it will enable debug log. If you'd like to share some debug logs here, I will take a closer look.

**Comment by marcusbake22** [comment]
![mad ma](https://github.com/KevCui/animepahe-dl/assets/156812295/621017b4-825b-49e5-b9bc-d1918409a7f4)

@KevCui why isn't the script working

**Comment by KevCui** [comment]
Hey @marcusbake22, it looks like you are in the wrong directory `~/Documents` where script is not present. You need to `cd` to the right directory and then run script.

**Comment by KevCui** [comment]
Hey @marcusbake22, since I haven’t heard from you in the last two months, I assume you’ve resolved your issue? I'm closing this issue ticket. If you still have trouble, feel free to add a comment and let me know.
