### ISSUE TITLE
Getting error: Failed to connect to eu-02.files.nextcdn.org

### ISSUE THREAD

**Issue by savanchhayani** [KevCui/animepahe-dl#105]
I am getting the following error, Can anyone please help me to fix it?

[INFO] Downloading Episode 1...
curl: (28) Failed to connect to eu-02.files.nextcdn.org port 443 after 5005 ms: Timeout was reached
[WARNING] Download was aborted. Retry...
curl: (28) Failed to connect to eu-02.files.nextcdn.org port 443 after 5006 ms: Timeout was reached

Thank you :)

**Comment by KevCui** [comment]
Hey @savanchhayani, it looks like a network issue or server issue. May I ask which anime you were downloading when you got this error?

**Comment by savanchhayani** [comment]
I am running the following command:
`./animepahe-dl.sh -a "chainsaw man" -t 43 -o jpn`

Moreover, I tried to run without `-t` and verified with different anime and still got the same error.

**Comment by KevCui** [comment]
Hey @savanchhayani, I can also see the same error. However, video can still be downloaded. If y wait for download finished, you will get the video. There is retry mechanism in the script, feel free to ignore those network errors.

**Comment by savanchhayani** [comment]
Okay, I will check :) 
Thank you 👍
