### ISSUE TITLE
Missing video list

### ISSUE THREAD

**Issue by marcusbake22** [KevCui/animepahe-dl#107]
Hey @marcusbake22, since I haven’t heard from you in the last two months, I assume you’ve resolved your issue? I'm closing this issue ticket. If you still have trouble, feel free to add a comment and let me know.

_Originally posted by @KevCui in https://github.com/KevCui/animepahe-dl/issues/103#issuecomment-2153427407_
           
![Screenshot 2024-09-15 141952](https://user-images.githubusercontent.com/156812295/367581019-8e563054-33c3-4bf8-bac1-aa835227f8ae.jpg)

can you help me its been months i took a break from anime since it wasn;t workin,how can i solve it

**Comment by KevCui** [comment]
Hey @marcusbake22, your screenshot in your comment doesn't display. Did you check my comment in old issue ticket: `it looks like you are in the wrong directory ~/Documents where script is not present. You need to cd to the right directory and then run script.`?

**Comment by marcusbake22** [comment]
@KevCui 
![Screenshot 2024-09-24 103458](https://github.com/user-attachments/assets/02e544b0-2a8b-42dc-8eca-8f42629b1236)

**Comment by KevCui** [comment]
Hey @marcusbake22, good to know it works now.
