### ISSUE TITLE
Getting Failed to connect error

### ISSUE THREAD

**Issue by rayn000** [KevCui/animepahe-dl#108]
Getting this error continuously. Tried without threads, without selecting language etc.

![image](https://github.com/user-attachments/assets/e74bc1b3-8a99-43a8-9c06-35c85c70542e)

**Comment by KevCui** [comment]
Hey @rayn000, it looks like a network issue, which doesn't relate to the script itself. Since the retry mechanism is still working, it may take longer to download but it will continue downloading.

**Comment by rayn000** [comment]
@KevCui Just to be clear, is it my side of network issue or pahe itself? If it is pahe side can you do something to rid of this? It's inconsistent.

I really love the convenience of your script : )

**Comment by KevCui** [comment]
Hey @rayn000, I'm closing this issue ticket since no update from you after one month. Feel free to continue posting your follow-up question here or open a new ticket if you have other issue. Cheers!
