### ISSUE TITLE
"Anime name not found!" and "Anime slug not found!"

### ISSUE THREAD

**Issue by jayjayglows** [KevCui/animepahe-dl#109]
Trying to download all of Nichijou and it threw "Anime name not found" at me. Looked around the rest of the resolved issues here for answers but nothing made sense or worked. Tried "bash animepahe-dl.sh" and while it did seemingly update the anime list file, it still gave me the same "name not found" error. I have approx 0 experience with doing things like these so I'm clueless as to what to do.
Image if it helps. Thanks :-)
![image](https://github.com/user-attachments/assets/4f8ad6fc-d2a9-48b4-afc6-425cc0016703)

**Comment by KevCui** [comment]
Hey @jayjayglows, I can see Nichijou has a different slug/UUID. You can use anime name `-a Nichijou` to find anime. Or get the new UUID from `anime.list` file on your script directory. Either option should fix this error. Let me know if works for you.

**Comment by KevCui** [comment]
Hey @jayjayglows, it looks like curl issue or network issue on your machine. We had similar one in #91. Unfortunately, I don't think it can be fixed inside the script. Hope you can find a solution soon. Good luck.
