### ISSUE TITLE
add choice for downloading using animepahe

### ISSUE THREAD

**Issue by lelouchvibritannia1** [KevCui/animepahe-dl#19]
Add choice for downloading videos through aria2 or other external downloaders.
Since there is no progress bar while downloading, I cannot be sure whether the file is downloading. So, its better to add an external downloader option like aria2 or atleast a progressbar. And could you please make sure that whatever external downloader you add, it runs on termux?
Thanks for looking

**Comment by KevCui** [comment]
Hi @lelouchvibritannia1, this issue title is too general. Which choice you would like to have? Would you provide more info in the description?

**Comment by KevCui** [comment]
Thanks @lelouchvibritannia1 for the idea. Regarding the progress bar, I'd say it's a nice to have feature. If you want to know the progress, you could run command `watch ls -lh "<video_file>"` to see the file size increasing. Hope this will help.
