### ISSUE TITLE
Ranges in episodes

### ISSUE THREAD

**Issue by smhmd** [KevCui/animepahe-dl#2]
The ability to download/list ranges: `1-100` to mean from episode 1 to episode 100. Better than: `1,2,3..,100`. Apologies if this is implemented but I couldn't figure it out.

**Comment by KevCui** [comment]
No worry, it's not implemented. I thought about that, on the other hand, using a `for` loop to iterate a range and run the script is already pretty handy. That's why I didn't add the function to use the range of episodes as input.

**Comment by smhmd** [comment]
Got you. However, writing `for` loops in the command line is really daunting. I would say the whole output of `animepahe-dl -s [slug]` is a bit rough, tbh. I would suggest a `-v, --verbose` flag because having a big list of metadata (with date) is always necessary. You could check https://github.com/vignedev/twist-dl (on `master` branch and merge `autoselect` branch). It could use a keymap for selecting/deselecting all, but it's quite nice.

I think it's important to output how many episodes are there. The syntax `1-20,25,30-40` would work great, I think. If you can make it so that having no input (on enter) would mean `all`, that would be good. Same goes for the flag `-e`.

**Comment by KevCui** [comment]
Alright, let me check if I can make the syntax you mentioned `1-20,25,30-4` work in the script.

**Comment by KevCui** [comment]
@smhmd The episode range is implemented in this commit. Would you like to give it a try? Hope you'll be happy fort that :)

**Comment by smhmd** [comment]
Works great! You got it.
