### ISSUE TITLE
file.list not found

### ISSUE THREAD

**Issue by uali6981** [KevCui/animepahe-dl#20]
on parallel threads `ffmpeg` give me this error

![image](https://user-images.githubusercontent.com/56256581/106558121-066eb700-6545-11eb-85a8-0ddbe35c8a1d.png)

**Comment by KevCui** [comment]
Hi @uali6981, the error indicates the `segment-1-v1-a1.ts` is not downloaded correctly. It may cause by some network hiccups. Did you try to launch the script again?

If you run script again and it's still not working, could you try to run script using normal download mode without option `-t`?

**Comment by uali6981** [comment]
launching script again after updating `ffmpeg` give me this error
![image](https://user-images.githubusercontent.com/56256581/106585927-adfde080-6569-11eb-8798-cfb88095257a.png)

and manually download work fine
![Screenshot 2021-02-02 150908](https://user-images.githubusercontent.com/56256581/106586045-cff76300-6569-11eb-92d8-77464301e864.png)

**Comment by KevCui** [comment]
@uali6981 ok, thanks for the info.

From the log, it shows that you are running with debug mode `-d`, this is good. `D:/d/...` part looks weird, it may cause the issue. Would you like to list the files in `D:/Projects/animepahe-dl/22_7/.1/`

**Comment by uali6981** [comment]
here

![image](https://user-images.githubusercontent.com/56256581/106594095-7300aa80-6573-11eb-9a7e-6426a4af898c.png)

**Comment by uali6981** [comment]
when I delete `/d` from here like
![image](https://user-images.githubusercontent.com/56256581/106605280-87986f00-6582-11eb-996e-4b31a147c2d9.png)


work fine for me
![image](https://user-images.githubusercontent.com/56256581/106605430-b6164a00-6582-11eb-914f-f3e7a17e3685.png)


so is there any way to not put `/d` from begining?

**Comment by uali6981** [comment]
Somehow I solve the issue but after downloading one ep next one did not start downloading automatically in batch downloading

**Comment by djchittoor** [comment]
Hi, Are you using WSL?

**Comment by uali6981** [comment]
I am on Windows.

**Comment by djchittoor** [comment]
> I am on Windows.

Well there you go, add handling to windows without breaking it on Linux also can you send me the output of `cd && pwd`

**Comment by uali6981** [comment]
> cd && pwd

like this?
![image](https://user-images.githubusercontent.com/56256581/106646266-5b471780-65af-11eb-8fad-dc2665a116d1.png)

**Comment by djchittoor** [comment]
> > cd && pwd
> 
> like this?
> ![image](https://user-images.githubusercontent.com/56256581/106646266-5b471780-65af-11eb-8fad-dc2665a116d1.png)

nono, just do the commands as such `cd && pwd`  
`cd` will by default change your directory to you home and `pwd` will print the working directory

**Comment by uali6981** [comment]
here
![image](https://user-images.githubusercontent.com/56256581/106737781-e9b3ab80-6638-11eb-9e57-bb65ba091192.png)

**Comment by KevCui** [comment]
Hi @uali6981, I made the first attempt to fix this issue in the latest commit. Let me know if it works for you or not.

**Comment by uali6981** [comment]
> Hi @uali6981, I made the first attempt to fix this issue in the latest commit. Let me know if it works for you or not.

here again give me error
![image](https://user-images.githubusercontent.com/56256581/106811884-c87ea980-6690-11eb-99bc-20f927b96bfc.png)

**Comment by uali6981** [comment]
is this type of approach not good?
![image](https://user-images.githubusercontent.com/56256581/106815754-1fd34880-6696-11eb-82ed-61c6bbfaa4c3.png)

**Comment by KevCui** [comment]
@uali6981 The approach your showed in the screenshot may work for you on win, but I don't think it works well for the others using linux. As @djchittoor mentioned, it has to be a solution without breaking things on linux.

As my first attempt to fix this issue is not working, then I will take another look.

**Comment by KevCui** [comment]
Hi @uali6981 could you please try the last commit? It's my second attempt to fix this issue. Hope this time it will work. :crossed_fingers:

**Comment by uali6981** [comment]
> Hi @uali6981 could you please try the last commit? It's my second attempt to fix this issue. Hope this time it will work. 🤞

working now thanks!
![image](https://user-images.githubusercontent.com/56256581/106997402-a413f180-67a4-11eb-8352-729f256e8564.png)



and is batch download work with window and parallal thread?

**Comment by KevCui** [comment]
@uali6981 Great, issue solved!

What do you mean batch download? If you mean `-e '*'` to download all episodes, then it should work in win.

**Comment by uali6981** [comment]
working

thank you so much for solving that issue
