### ISSUE TITLE
Can you please share how to use this on termux on phone?

### ISSUE THREAD

**Issue by danielr0206** [KevCui/animepahe-dl#22]

**Comment by KevCui** [comment]
Hi @danielr0206, I don't know how to run it on the phone. The script is not designed for the phone and I think it won't work.

**Comment by Akianonymus** [comment]
I would just like to point out that it would also work on termux, gotta install the dependencies.

```
pkg install fzf nodejs jq  ffmpeg
```

**Comment by danielr0206** [comment]
> I would just like to point out that it would also work on termux, gotta install the dependencies.
> 
> ```
> pkg install fzf nodejs jq  ffmpeg
> ```

TYVM
