### ISSUE TITLE
Can you please tell how to properly implement jq

### ISSUE THREAD

**Issue by Xtraneous69** [KevCui/animepahe-dl#26]
![Screenshot (4035)_LI](https://user-images.githubusercontent.com/82363558/115027522-68a94800-9ef6-11eb-9646-f72b09fc1f28.jpg)
I had already placed jq-win64.exe file in the same folder but I don't know what to do with it or how to use it, can you please explain in full detail for beginners like me, I'm quite new to bash scripts

**Comment by KevCui** [comment]
Hi @Xtraneous69, you can run command `echo $PATH` to see all path locations. Put jq binary in one of those location and rename it to `jq`, then check if `jq` binary location is picked up in the environment by running command `which jq`.

**Comment by Xtraneous69** [comment]
> Hi @Xtraneous69, you can run command `echo $PATH` to see all path locations. Put jq binary in one of those location and rename it to `jq`, then check if `jq` binary location is picked up in the environment by running command `which jq`.

thanks, I'll test it out

**Comment by KevCui** [comment]
@Xtraneous69 could you please run script with the flag `-d`, which enables debug mode and shows logs in the terminal. If you could share logs here, I will take a look.

**Comment by Xtraneous69** [comment]
> @Xtraneous69 could you please run script with the flag `-d`, which enables debug mode and shows logs in the terminal. If you could share logs here, I will take a look.

wait up, I managed to download an episode, and now I'm downloading 2 more, I'll get back to you when they're done
![Screenshot (4035)](https://user-images.githubusercontent.com/82363558/115222513-62f17380-a13d-11eb-8217-740cea4346ba.png)
![Screenshot (4036)](https://user-images.githubusercontent.com/82363558/115222519-64bb3700-a13d-11eb-8750-2bbce220b6ed.png)

**Comment by Xtraneous69** [comment]
> @Xtraneous69 could you please run script with the flag `-d`, which enables debug mode and shows logs in the terminal. If you could share logs here, I will take a look.

here ya go
![Screenshot (4037)](https://user-images.githubusercontent.com/82363558/115223655-a13b6280-a13e-11eb-8adf-e858d860880e.png)

**Comment by KevCui** [comment]
Hi @Xtraneous69, I don't see any errors in the logs you posted. From your screenshot, I assume that the command `./animepahe-dl.sh -s 8883bdd4-b11c-5495-36c4-197a5225c794 -t 120 -e 11,12` downloaded episodes 11 and 12 correctly? If it's not, please run command with the flag `-d`, like `./animepahe-dl.sh -s 8883bdd4-b11c-5495-36c4-197a5225c794 -t 120 -e 11 -d`, the logs may help. Thanks.

**Comment by Xtraneous69** [comment]
> Hi @Xtraneous69, I don't see any errors in the logs you posted. From your screenshot, I assume that the command `./animepahe-dl.sh -s 8883bdd4-b11c-5495-36c4-197a5225c794 -t 120 -e 11,12` downloaded episodes 11 and 12 correctly? If it's not, please run command with the flag `-d`, like `./animepahe-dl.sh -s 8883bdd4-b11c-5495-36c4-197a5225c794 -t 120 -e 11 -d`, the logs may help. Thanks.

yeah, I got it, when I moved the videos to my phone, it is laggy (some frame skips from time to time) but I'll try playing it in vlc application instead, I don't have any other issue spotted currently so I'll close this one. Have a great day.
