### ISSUE TITLE
no show of threads

### ISSUE THREAD

**Issue by raffyOmega** [KevCui/animepahe-dl#27]
I already download the openssl but still theres is no threads showned during downloading some series
![tread](https://user-images.githubusercontent.com/85740732/121676803-a76b1100-cae7-11eb-9d29-b3d506f3ee99.png)

**Comment by KevCui** [comment]
Hi @raffyOmega, from your screenshot, there is one space character between `-` and `r`. Remove that and try again?

**Comment by raffyOmega** [comment]
> Hi @raffyOmega, from your screenshot, there is one space character between `-` and `r`. Remove that and try again?

i fix it but...
![paild](https://user-images.githubusercontent.com/85740732/121683755-64616b80-caf0-11eb-8420-924346bb7fac.png)

**Comment by KevCui** [comment]
@raffyOmega Strange. Please run command with `-d` to enable debug mode and post some logs, I will take a look later.

**Comment by raffyOmega** [comment]
> @raffyOmega Strange. Please run command with `-d` to enable debug mode and post some logs, I will take a look later.

![2](https://user-images.githubusercontent.com/85740732/121758738-3d895080-cb55-11eb-8231-50d4ce1b4b00.png)
![1](https://user-images.githubusercontent.com/85740732/121758740-3f531400-cb55-11eb-8dfe-8de1e965c983.png)

**Comment by raffyOmega** [comment]
i have another problem while downloading some episodes
![bago](https://user-images.githubusercontent.com/85740732/121775659-92f84880-cbbb-11eb-889f-0bd8235093cd.png)

**Comment by KevCui** [comment]
Hi @raffyOmega, are you able to download any episode using normal download *without* `-t`? Could you try to install generic curl for Windows, not cygwin one?

**Comment by raffyOmega** [comment]
> Hi @raffyOmega, are you able to download any episode using normal download _without_ `-t`? Could you try to install generic curl for Windows, not cygwin one?
hello admin,
Yes I can but it take 10-20 mins per episode eventhough I  have an higher internet speed(230 mbps ) . I'll try to install

**Comment by KevCui** [comment]
Hi @raffyOmega, I made the attempt in the last commit to fix the problem. Could you pull the latest commit and try once more if `-t` works for you now?

**Comment by raffyOmega** [comment]
> Hi @raffyOmega, I made the attempt in the last commit to fix the problem. Could you pull the latest commit and try once more if `-t` works for you now?

![tin](https://user-images.githubusercontent.com/85740732/121798208-a0fba700-cc57-11eb-8d50-690224427682.png)
I can use"-t" command from other series but some series still error (curl)23

**Comment by raffyOmega** [comment]
![we](https://user-images.githubusercontent.com/85740732/121798307-12d3f080-cc58-11eb-9a40-1ef90b6e30e5.png)
![x](https://user-images.githubusercontent.com/85740732/121798318-2ed79200-cc58-11eb-8211-e938bc1c84a8.png)

**Comment by KevCui** [comment]
Hi @raffyOmega, the error may be caused by some special characters in folder name. I made some changes in the latest commit. If you pull the changes, your issue should be fixed.
