### ISSUE TITLE
no output shown

### ISSUE THREAD

**Issue by thaynos** [KevCui/animepahe-dl#28]
```
GUEST123@RICHU MINGW64 ~/Downloads/animepahe-dl-master (1)/animepahe-dl-master
$ ./animepahe-dl.sh -a "naruto"

```
after nothing shows

**Comment by KevCui** [comment]
Hi @thaynos, please run script with `-d` to enable debug mode, paste some logs here and I will take a look. Thanks.

**Comment by thaynos** [comment]
nothing happens?
`./animepahe-dl.sh -a "naruto" -d`

it just stays as a blank screen

**Comment by KevCui** [comment]
What?! This is unexpected 😓. @thaynos Try `bash -x ./animepahe-dl.sh -a "narutu"`?

**Comment by KevCui** [comment]
Close this issue for now, because info is missing for the further investigation.
