### ISSUE TITLE
Symbolic link issue

### ISSUE THREAD

**Issue by smhmd** [KevCui/animepahe-dl#3]
Linking `animepahe-dl.sh` somewhere (`~/.local/bin`) and using that breaks it:

![image](https://user-images.githubusercontent.com/46059092/94037327-c5a3ac00-fdb4-11ea-9d22-b38142a24847.png)

The error:
```
/home/me/.local/bin/animepahe-dl: line 159: /home/me/.local/bin/bin/getCFcookie.js: No such file or directory
[ERROR] Cannot fetch cf_clearance from https://kwik.cx/f/cBEjXgGPcFM2!
```

**Comment by KevCui** [comment]
I'd suggest to add `animepahe-dl` directory path in Shell `$PATH`. It will solve this missing file issue.

**Comment by smhmd** [comment]
I'm better off with an alias. You can make things relative to the script instead of using `$_SCRIPT_PATH`. If not, please feel free to close the issue as a `won't fix`.

**Comment by KevCui** [comment]
Ok, understand. It should be easy to resolve symbolic path. Let me check.

**Comment by KevCui** [comment]
Fixed! Please give it a try.
