### ISSUE TITLE
Download Error after working fine at first; error pasted bellow

### ISSUE THREAD

**Issue by prajwal108** [KevCui/animepahe-dl#30]
prajw@DESKTOP-39F45QH MINGW64 /d/animepahe-dl-master/animepahe-dl-master
$ ./animepahe-dl.sh -a 'one piece'
parse error: Invalid numeric literal at line 1, column 10
[ERROR] Anime slug not found!

**Comment by KevCui** [comment]
Same cause as #29

**Comment by KevCui** [comment]
Hi @prajwal108, please pull the latest commit, it should work.

**Comment by prajwal108** [comment]
it did worked !
Thank you so much for your help
