### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by TisIDom** [KevCui/animepahe-dl#36]
There's no audio on the anime episodes I've downloaded. Did I go wrong somewhere? All the dependencies, libraries, or whatever seem to be installed correctly.
Edit: Reinstalled the dependencies, tried downloading again but the same problem occurs.

**Comment by KevCui** [comment]
Hi @TisIDom, could you please check on the website if anime you want to watch has audio? The script only downloads the media to local. It should not cause this issue.

**Comment by TisIDom** [comment]
@KevCui  I downloaded it from Animepahe and yeah it does have audio on the website.

**Comment by KevCui** [comment]
@TisIDom Ok, I think it may have something to do with `ffmpeg`. Could you let me know which anime title and episode you want do download? And the version of `ffmpeg`, run `ffmpeg --version` to get version?

**Comment by TisIDom** [comment]
@KevCui
ffmpeg: ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
             built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
anime:  Steins;Gate, none of the episodes had sound.

**Comment by KevCui** [comment]
Hi @TisIDom, could you please run `./animepahe-dl.sh -s 5d309d45-d290-37dd-2665-0b84fb146830 -e 1 -d 2>&1 | tee debug.log`? It will download 1st ep of Steins;Gate and dump logs to `debug.log`. If you share `debug.log` in the comment or paste it to GitHub Gist, I will take a look. Thanks.

**Comment by TisIDom** [comment]
Hello @KevCui, here are the logs: https://gist.github.com/TisIDom/a94dfeaafad6e4a562155f90d088f082

Also, I was playing around with the episode file and after opening it with VLC Player, the audio started working. Maybe something's wrong with my installation of Microsoft's 'Movies & TV'? What's strange is that all of the other videos on my pc opened with Microsoft's 'Movies & TV' work fine audio-wise. I guess I'll just have to watch the episodes on VLC Player haha.
Thank you for trying to help me out!

**Comment by KevCui** [comment]
Hi @TisIDom, I'm glad that the audio works now for you. It's possible that Microsoft's 'Movies & TV' doesn't support certain audio codec. In the script, the audio codec used in `ffmpeg` is the default one (auto selected by ffmpeg). From your log file, it's `Audio: aac (HE-AAC) `. If you want to use Microsoft's 'Movies & TV', I think you could search online and maybe there are some additional codec to install for Microsoft's 'Movies & TV'.
