### ISSUE TITLE
SSL CONNECTION TIMEOUT

### ISSUE THREAD

**Issue by Zeroo097** [KevCui/animepahe-dl#40]
When i try to download using -t command it shows connection timeout.

Command I Used:-
./animepahe-dl.sh -s (anime slug) -r 720 -e 2-11 -t 5

![IMG_20211005_220014.jpg](https://user-images.githubusercontent.com/91909890/136065762-429fa948-e3d2-43b2-9a67-caf9228e2b2e.jpg)

**Comment by KevCui** [comment]
Hi @Zeroo097, I'm aware of that and I did some investigations. So far, I'd say it's caused by network issue or server side throttling. I suggest to use normal download mode without `-t`.

**Comment by Zeroo097** [comment]
Sir,I Cannot use normal download feature because AnimePahe.com is banned in our country and i have to use vpn which give very slow data speed.Openssl helped in increasing speed a little bit.Is there any workaround that i can use AnimePahe.ru which is not banned in and i can use it without vpn which will aug increase data speed.

**Comment by KevCui** [comment]
Hi @Zeroo097, you could try to change URL in the script to use the ru one. However, I never tried to use the ru one. It's not guarantee that it will work through. Well, at least, please give it a try.

**Comment by Zeroo097** [comment]
Okay i will try it and then update you.

**Comment by Zeroo097** [comment]
Okay in the beginning of the script i changed .com to .ru and when i ran the script it showed parse error btw i only changed the host written in the beginning nothing else.

![IMG_20211006_142644.jpg](https://user-images.githubusercontent.com/91909890/136174277-cb174e02-5a27-4e68-b67b-ac3c22471f8c.jpg)
