### ISSUE TITLE
Issue while downloading

### ISSUE THREAD

**Issue by Karambe69** [KevCui/animepahe-dl#41]
I was downloading mha,the first day it worked fine.But nowadays whenever i use -t for better download speed it shows ssl connection aborted however the downloading doesn't stop.But Still.

**Comment by mxmxrp** [comment]
> I was downloading mha,the first day it worked fine.But nowadays whenever i use -t for better download speed it shows ssl connection aborted however the downloading doesn't stop.But Still.

do you have a solution for this issue?
