### ISSUE TITLE
Help bro...!!!

### ISSUE THREAD

**Issue by Sunderlevi** [KevCui/animepahe-dl#43]
1.Does this downloader shows downloading percent while downloading or it is not showing to me.
2.I tired using -t but it's not working any solution

**Comment by KevCui** [comment]
Hi @Sunderlevi,

1. no progress bar, normal for everyone
2. no idea, share some logs or error messages?

**Comment by Sunderlevi** [comment]
![Screenshot_2022-01-24-06-49-11-69_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/96936021/150707517-2ce25b7b-5e46-4d50-8907-89191e95c4c4.png)
Can you update the code with progress bar 
It actually very difficult to say when the downloading will be finished..

**Comment by KevCui** [comment]
Hi @Sunderlevi, regarding progress bar and how to check download progress, please reed https://github.com/KevCui/animepahe-dl/issues/19#issuecomment-772817109

For error message you saw in the screenshot, it's normal, as I mentioned in the READM.md:

> ⚠️ Be aware that the parallel download feature can be sometimes unstable, depending on the server side throttling. But usually, it should be stable with a number of threads below 50.

You could try to reduce `-t` value or use normal download mode without `-t`. Hope it will work for you.
