### ISSUE TITLE
Petition

### ISSUE THREAD

**Issue by Sunderlevi** [KevCui/animepahe-dl#44]
Add animepahe scrap link batch to download externally if possible...

**Comment by KevCui** [comment]
Hi @Sunderlevi, if I understand your suggestion correctly, it's been done already in the script. You could use the `-l` flag:

>   -l                      optional, show m3u8 playlist link without downloading videos

**Comment by Sunderlevi** [comment]
Can give me an example command line

**Comment by KevCui** [comment]
Hi @Sunderlevi, if you see 403 error, please check the request header. The referer header is required `Referer: https://kwik.cx/`. Check out README.md if you need an example using `mpv`.
