### ISSUE TITLE
Can't load the list

### ISSUE THREAD

**Issue by karmakarmeghdip** [KevCui/animepahe-dl#45]
I tried running it this morning and it ran flawlessly, everything was fine, but when I tried downloading the next episode, the list was entirely 0/0,
This was the error: `curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to animepahe.com:443`

Pls help 🥺

**Comment by KevCui** [comment]
Hi @karmakarmeghdip, from the error message you posted, it looks like a connection issue from server side. Maybe try it later? Hope it will work.
