### ISSUE TITLE
Sorry again for bothering

### ISSUE THREAD

**Issue by Sunderlevi** [KevCui/animepahe-dl#47]
Is there any way to increase the download speed
Like using VPN or something....
The speed of my net is around 8 to 10 mps speed
But the downloading is very slow...

**Comment by KevCui** [comment]
Hi @Sunderlevi, I'd suggest to try the flag `-t` to enable parallel download, it may gain some speed. Overall, the download speed is throttled on the server side, which I don't have the control of :(
