### ISSUE TITLE
Video and audio out of sync

### ISSUE THREAD

**Issue by Sunderlevi** [KevCui/animepahe-dl#48]
Sorry bro agian disturbing you...
When I use thread mode it's complete's the given task but the downloaded video audio and video not sync together....
Any solution..???
And again sorry for opening a new issue

**Comment by KevCui** [comment]
Hi @Sunderlevi, it shouldn't be. Did you check the video on the website if it's not broken by default? Or you can tell me the anime name and episode, I can quickly check.

**Comment by KevCui** [comment]
What's the `ffmpeg` version you have? Maybe the audio issue is caused by it.

**Comment by Sunderlevi** [comment]
No its not from the website
Anime:- Jujutsu Kaisen
My ffmpeg version is 5.0

**Comment by KevCui** [comment]
@Sunderlevi This sync issue only happens in this anime or other as well? Did you try to download using normal speed without parallel download?

**Comment by KevCui** [comment]
Hi @Sunderlevi, I assume it's an issue of `ffmpeg`. But after I searched around, I didn't find any clue... If you could run the script with `-d` flag to enable debug mode, and paste some logs here, I may take a look.

**Comment by Sunderlevi** [comment]
Sorry for the late response
As you said I also kinda looked around and I figured out the problem.
I just updated some parts of my program and the problem was solved....
Thanks again man for helping me out....
And one small Request
If you are going upgrade/update the program in the near future please can add the feature of showing downloading percent...😄

**Comment by KevCui** [comment]
Hi @Sunderlevi good to hear that it's now working for you. So far, I don't plan to add a progress bar. If someone wants to add it, be my guest 🙂
