### ISSUE TITLE
Use names, not slugs

### ISSUE THREAD

**Issue by smhmd** [KevCui/animepahe-dl#5]
If I'm not mistaken, slugs get outdated, making history obsolete every now and then. `fzf` can take a filter flag `-f, --filter` to return the best matches in order. Combined with `head`, a flag of `-n, --name` (or `-a`) would be much durable. 

```fish
$ animepahe-dl -a anime -e 1-50 -l
```

(Does Animepahe not support English titles?)

```fish
$ animepahe-dl
  .
  .
  Danshi Koukousei no Nichijou [Daily Lives of High School Boys]
> Shingeki no Kyojin [Attack on Titan]
  3693/3693
>
```

To tell you the truth, I don't know why slugs are involved to begin with. Since they get outdated, it seems sensible to abstract them away. Is there a reason, @KevCui?

**Comment by smhmd** [comment]
A flag to use `fzf`'s `--query` flag instead of `--filter` could work great, too.

**Comment by KevCui** [comment]
Hey @smhmd, the anime name flag sounds good. Since you already digged deeper and have the idea how to achieve it. Would you mind to make a PR?

**Comment by KevCui** [comment]
There is a search API which supports searching anime English title. However, the response of this API doesn't include English title... only Japanese one. In the case you mentioned above, now you can search anime by its English title, e.g.: `./animepahe-dl.sh -a 'attack on titan'`
