### ISSUE TITLE
Can't download Shingeki no Kyojin in japanese audio

### ISSUE THREAD

**Issue by love4589** [KevCui/animepahe-dl#51]
When given -o 'jpn', output is:
[WARNING] Missing video list! Skip downloading!
Same happens if I don't give -o argument

When given -o 'eng', it works as expected.

**Comment by love4589** [comment]
!bash /content/animepahe-dl/animepahe-dl.sh  -t 10 -e '*' -s 4982a240-207e-08ae-c29f-93e879f11b01

[INFO] Downloading Episode 1...
[INFO] Start parallel jobs with 10 threads
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!
[WARNING] Missing video list! Skip downloading!

Downloaded is in english lang.

**Comment by KevCui** [comment]
Hi @love4589, I tried your command and it works for me. If you check the same anime on the animepahe site, you will see a warning: ` We are getting a lot of traffic because of Shingeki no Kyojin and Kimetsu no Yaiba right now, you may experience lags, a lot of lags, during streaming. `.

This is a server side issue and it's not related to this script. I assume if you try it again now, it should work.
