### ISSUE TITLE
anime.list not updating

### ISSUE THREAD

**Issue by love4589** [KevCui/animepahe-dl#52]
Until yesterday noon it worked flawlessly, but after that it is not updating, like no anime slug and name. Can you please look into it. Thanks

**Comment by love4589** [comment]
+ getopts :hlda:s:e:r:t:o: opt
+ set_var
++ command -v curl
+ _CURL=/usr/bin/curl
++ command -v jq
+ _JQ=/usr/bin/jq
++ command -v fzf
+ _FZF=/bin/fzf
++ command -v node
+ _NODE=/tools/node/bin/node
++ command -v ffmpeg
+ _FFMPEG=/usr/bin/ffmpeg
+ [[ 1 -gt 1 ]]
+ _HOST=https://animepahe.com/
+ _ANIME_URL=https://animepahe.com/anime
+ _API_URL=https://animepahe.com/api
+ _REFERER_URL=https://kwik.cx/
+++ realpath /content/animepahe-dl/animepahe-dl.sh
++ dirname /content/animepahe-dl/animepahe-dl.sh
+ _SCRIPT_PATH=/content/animepahe-dl
+ _ANIME_LIST_FILE=/content/animepahe-dl/anime.list
+ _SOURCE_FILE=.source.json
+ _COOKIE=__ddg2=
+ [[ -n '' ]]
+ download_anime_list
+ /usr/bin/curl --compressed -sS https://animepahe.com/anime -H 'Cookie: __ddg2='
+ sed -E 's/.*anime\//[/;s/" title="/] /;s/\">.*//'
+ grep /anime/
+ [[ -z '' ]]
++ /bin/fzf
++ remove_brackets
++ awk '-F]' '{print $1}'
++ sed -E 's/^\[//'

Its stuck here forever

**Comment by KevCui** [comment]
Hey @love4589, there were some changes on the server side. The script needs to adapt to those changes in order to work again...

**Comment by love4589** [comment]
It seems the same to me. I got it. Will be looking forward. _Ciao_

**Comment by KevCui** [comment]
Hey @love4589, the fix is added in the latest commit. It now requires to install additional npm packages. Please read https://github.com/KevCui/animepahe-dl#installation for more details. The script should work again.
