### ISSUE TITLE
[ERROR] chrome command not found 

### ISSUE THREAD

**Issue by Anime-Tako** [KevCui/animepahe-dl#53]
I'm really sorry bout this I just really don't know what to do, I downloaded the latest commit, installed the npm packages and downloaded chrome/chromium but it still doesn't work for me. Please help.  I copied the error i get below, thanks in advance.
./animepahe-dl.sh: line 37: command not found
[ERROR] chrome command not found

**Comment by KevCui** [comment]
Hey @Anime-Tako, could you check the PATH variable `echo $PATH`, and put chrome binary into one of the path? This should help the system to find the chrome. Let me know if this works for you.

**Comment by Anime-Tako** [comment]
Hello, I tried doing what you suggested. The error no longer appears but i am still unable to download. What happens now is that after I tried entering (i.e ./animepahe-dl.sh -s 113bd27d-b06c-e940-993e-06072bbbaec9 -e 1 -r 1080) the error no longer appears and the chrome app opens and thats it. The download still doesn't start.

**Comment by KevCui** [comment]
@Anime-Tako Try `./animepahe-dl.sh -s 113bd27d-b06c-e940-993e-06072bbbaec9 -e 1 -d` and it will print out debug logs. If you could paste some logs here, I will help to take a look.

**Comment by Anime-Tako** [comment]
Hi, sorry for the delay, here's what i got. The chrome browser still opened.
+ getopts :hlda:s:e:r:t:o: opt
+ set_var
++ command -v curl
+ _CURL=/mingw64/bin/curl
++ command -v jq
+ _JQ=/c/ProgramData/chocolatey/bin/jq
++ command -v fzf
+ _FZF=/c/ProgramData/chocolatey/bin/fzf
++ command -v node
+ _NODE='/c/Program Files/nodejs/node'
++ command -v ffmpeg
+ _FFMPEG=/c/ProgramData/chocolatey/bin/ffmpeg
++ command -v chromium
+ _CHROME=
++ command -v chrome
+ '/c/Program Files/Google/Chrome/Application/chrome'

**Comment by KevCui** [comment]
Hey @Anime-Tako, thanks for the logs. It was my terrible coding mistake. Now, it's fixed in the latest commit.

**Comment by nareik26** [comment]
> [Anime-Tako](/Anime-Tako)

how did you put chrome binary into one of the path?
