### ISSUE TITLE
Chrome command not found

### ISSUE THREAD

**Issue by nareik26** [KevCui/animepahe-dl#55]
Chrome command not found I already installed the npm 

my command is:
./animepahe-dl.sh -a 'ousama ranking' -e 1-23 -r 1080

**Comment by KevCui** [comment]
Hey @nareik26, could you check the PATH variable `echo $PATH`, and put chrome binary into one of the path? This should help the system to find the chrome. Let me know if this works for you.

**Comment by nareik26** [comment]
Sorry in advanced don't know how to how to put the chrome binary into one of the path.

**Comment by KevCui** [comment]
Hey @nareik26, pretty sure you may find the solution somewhere online. Try google it? :)

**Comment by imu1** [comment]
> Sorry in advanced don't know how to how to put the chrome binary into one of the path.
You really need a separate chrome install.
In this case, you can just use chromium.
1. Download a copy of chromium here: https://download-chromium.appspot.com/. It will download a zip file named: `chrome-win.zip` 185 MB
2. Open the Git Bash terminal in the animepahe-dl.sh file (right click -> "Git Bash Here")
3. Type the following to get a human-readable list of paths: `tr ':' '\n' <<< "$PATH"`
4. Go to `C:/Users/YOURCURRENTWINDOWSNAME/bin`. If the bin folder doesn't exist, you can create it
5. Extract the chrome-win.zip files into the `C:/Users/YOURCURRENTWINDOWSNAME/bin` path.
6. Once you extracted chromium there, close the cmd windows, and open git bash on the animepahe folder.
You should be able to run the commands at this point

**Comment by KevCui** [comment]
Hey @nareik26, chrome/chromium is not needed in the latest commit. Please pull the changes and give it a try.

**Comment by nareik26** [comment]
Thank you
