### ISSUE TITLE
Stuck on getting cookies

### ISSUE THREAD

**Issue by love4589** [KevCui/animepahe-dl#58]
log---------

$ bash animepahe-dl.sh -d
+ getopts :hlda:s:e:r:t:o: opt
+ set_var
++ command -v curl
+ _CURL=/mingw64/bin/curl
++ command -v jq
+ _JQ=/c/ProgramData/chocolatey/bin/jq
++ command -v fzf
+ _FZF=/c/ProgramData/chocolatey/bin/fzf
++ command -v node
+ _NODE='/c/Program Files/nodejs/node'
++ command -v ffmpeg
+ _FFMPEG=/c/WINDOWS/system32/ffmpeg
++ command -v chromium
+ _CHROME=
++ command -v chrome
+ _CHROME='/c/Program Files/Google/Chrome/Application/chrome'
+ [[ 1 -gt 1 ]]
+ _HOST=https://animepahe.com
+ _ANIME_URL=https://animepahe.com/anime
+ _API_URL=https://animepahe.com/api
+ _REFERER_URL=https://kwik.cx/
+++ realpath animepahe-dl.sh
++ dirname /c/Git/animepahe-dl/animepahe-dl.sh
+ _SCRIPT_PATH=/c/Git/animepahe-dl
+ _ANIME_LIST_FILE=/c/Git/animepahe-dl/anime.list
+ _SOURCE_FILE=.source.json
+ _COOKIE_FILE=/c/Git/animepahe-dl/cookie.json
+ _USER_AGENT_FILE=/c/Git/animepahe-dl/user-agent
+ _USER_AGENT_LIST_FILE=/c/Git/animepahe-dl/user-agent.list
+ _GET_COOKIE_JS=/c/Git/animepahe-dl/bin/getCookie.js
+ [[ -s /c/Git/animepahe-dl/user-agent ]]
++ cat /c/Git/animepahe-dl/user-agent
+ _USER_AGENT='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2'
+ [[ -n '' ]]
+ download_anime_list
+ get https://animepahe.com/anime
+ local cookie
+ grep /anime/
++ get_cookie
+ sed -E 's/.*anime\//[/;s/" title="/] /;s/\">.*//'
+++ is_file_expired /c/Git/animepahe-dl/cookie.json 120
+++ local o
+++ o=yes
+++ [[ -f /c/Git/animepahe-dl/cookie.json ]]
+++ echo yes
++ [[ yes == \y\e\s ]]
++ local cookie
++ print_info 'Wait a few seconds for fetching cookie...'
++ [[ -z '' ]]
++ printf '%b\n' '\033[32m[INFO]\033[0m Wait a few seconds for fetching cookie...'
[INFO] Wait a few seconds for fetching cookie...
+++ /c/Git/animepahe-dl/bin/getCookie.js '/c/Program Files/Google/Chrome/Application/chrome' https://animepahe.com 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2'
++ cookie=
++ [[ -z '' ]]
++ get_cookie
+++ is_file_expired /c/Git/animepahe-dl/cookie.json 120
+++ local o
+++ o=yes
+++ [[ -f /c/Git/animepahe-dl/cookie.json ]]
+++ echo yes
++ [[ yes == \y\e\s ]]
++ local cookie
++ print_info 'Wait a few seconds for fetching cookie...'
++ [[ -z '' ]]
++ printf '%b\n' '\033[32m[INFO]\033[0m Wait a few seconds for fetching cookie...'
[INFO] Wait a few seconds for fetching cookie...
+++ /c/Git/animepahe-dl/bin/getCookie.js '/c/Program Files/Google/Chrome/Application/chrome' https://animepahe.com 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2'
++ cookie=
++ [[ -z '' ]]
++ get_cookie
+++ is_file_expired /c/Git/animepahe-dl/cookie.json 120
+++ local o
+++ o=yes
+++ [[ -f /c/Git/animepahe-dl/cookie.json ]]
+++ echo yes
++ [[ yes == \y\e\s ]]
++ local cookie
++ print_info 'Wait a few seconds for fetching cookie...'
++ [[ -z '' ]]
++ printf '%b\n' '\033[32m[INFO]\033[0m Wait a few seconds for fetching cookie...'
[INFO] Wait a few seconds for fetching cookie...
+++ /c/Git/animepahe-dl/bin/getCookie.js '/c/Program Files/Google/Chrome/Application/chrome' https://animepahe.com 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2'
++ cookie=
++ [[ -z '' ]]
++

**Comment by KevCui** [comment]
Hey @love4589, apparently the cookies are no longer needed. I removed the usage in the latest commit. Please give it a try.

**Comment by KevCui** [comment]
Hey @love4589, since I didn't get your feedback, I assume the script is working for you now. I will close this issue and if you still face the problem, please let me know and I will take another look.
