### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by testbughub** [KevCui/animepahe-dl#59]
Just started getting this error today (was working yesterday):

```
parse error: Invalid literal at line 1, column 4
```

Also, I've previously posted an issue about the date error, but the script still worked so I didn't really care about it,
although I can add that the date error doesn't appear on the first line if I remove the old cookie.json before executing the script.

Example:
(no cookie.json)
```
$ ./animepahe-dl.sh -r "720" -a "world trigger"
[INFO] Wait a few seconds for fetching cookie...
date: invalid date ‘sön 17 apr 2022 16:38:17 CEST +120 minutes’
[INFO] Wait a few seconds for fetching cookie...
date: invalid date ‘sön 17 apr 2022 16:38:21 CEST +120 minutes’
[INFO] Wait a few seconds for fetching cookie...
```
(with cookie.json)
```
$ ./animepahe-dl.sh -r "720" -a "world trigger"
date: invalid date ‘sön 17 apr 2022 16:38:22 CEST +120 minutes’
[INFO] Wait a few seconds for fetching cookie...
date: invalid date ‘sön 17 apr 2022 16:38:47 CEST +120 minutes’
[INFO] Wait a few seconds for fetching cookie...
date: invalid date ‘sön 17 apr 2022 16:38:55 CEST +120 minutes’
[INFO] Wait a few seconds for fetching cookie...
```

**Comment by KevCui** [comment]
Hey @testbughub, apparently the cookies are no longer needed. I removed the usage in the latest commit. Please give it a try.

**Comment by testbughub** [comment]
Yep, works perfectly now! Thanks a bunch!
