### ISSUE TITLE
Question/enhancement

### ISSUE THREAD

**Issue by testbughub** [KevCui/animepahe-dl#60]
Hi there, me again!

Just had a quick question;
Would it be possible to when searching for an anime to only get the 
anime titles in the fzf list, instead of including the slug before it?

The reason I ask is that I usually use my phone to download everything to my server through SSH, 
and because of the small screen size I have to rotate my phone (almost) every time to see which title 
I have selected (and sometimes I can't even see the whole title with those anime's that has really long names). 

Not the biggest issue in the world, but it can be a pain at times. 

No worries if it's too much of a hassle, but I think it'd be the cherry on top for this lovely script! 😃

**Comment by KevCui** [comment]
Hey @testbughub, thanks for the feedback. The last commit contains the changes to show only the anime name in fzf. Enjoy! :cherries:
