### ISSUE TITLE
Getting the OVA version instead of the 'normal' one

### ISSUE THREAD

**Issue by testbughub** [KevCui/animepahe-dl#61]
Hi again.

I really hope I'm not being annoying by adding more issues here,
but putting my own insecurities aside, I just noticed a weird one just now.

When I selected "Shijou Saikyou no Deshi Kenichi" (non OVA), 
I kept getting the listed episodes from the OVA instead.

Hopefully it's an easy fix.

I'd love to help out with fixes, but I feel that this is just beyond my skill level unfortunately,
but I plan on going through the commands at some point to figure out how it all works.

Thanks for your awesome work and for the quick fixes you do!

On a side note, do you have a PayPal or something? 
I'd love to give you some tip considering I use this so frequently.

**Comment by testbughub** [comment]
I just realized that it works fine by using the slug id. Could be something about those?

**Comment by KevCui** [comment]
Hey @testbughub, I see, it's my mistake. The fix is in the latest commit. Give it a try.

**Comment by KevCui** [comment]
Thanks @testbughub for considering tipping :bow: You could find my [paypal link](https://paypal.me/kevcui), much appreciated!

**Comment by testbughub** [comment]
Much appreciated!
I'll be sure to give you a little something on my next paycheck in two days :smiley:
