### ISSUE TITLE
Downloading folder ends with two whitespaces

### ISSUE THREAD

**Issue by testbughub** [KevCui/animepahe-dl#62]
Hi again!

Not sure what caused it, when looking through the fzf list and when it downloads the episode(s),
it adds two spaces to the dir name.
I tried looking for the cause, but didn't have any luck with it. 
I'm only guessing that it's related to the $_ANIME_NAME variable.

Everything else still works fine though, so no need to rush anything :smiley:

**Comment by KevCui** [comment]
Hi @testbughub, that's right, using the trailing spaces is a quick hack to avoid select wrong anime name. I thought no one would notice those 3 spaces in the folder name. Apparently, this assumption is wrong. I will find a proper way to solve the problem :)

**Comment by KevCui** [comment]
Hey @testbughub, the latest commit should fix this issue. Give it a try.

**Comment by testbughub** [comment]
@KevCui Ah, I see. Well the only reason I noticed it is because I move some episodes to a different folder 
so I can view them on my Emby server, 
and because I use zsh + ohmyzsh with the zsh-autosuggestions plugin ([quick example](https://0x0.st/oAXp.png
)), 
it complained that it couldn't find the file when I 'tabbed' which gave me a short "wtf" moment :sweat_smile:.

But it works fine again like you mentioned. 
Thanks!
