### ISSUE TITLE
Missing Video list

### ISSUE THREAD

**Issue by ricky16x** [KevCui/animepahe-dl#63]
Please help with the error.

![image](https://user-images.githubusercontent.com/35138477/167368669-8649c0a8-1b73-4dbb-adc6-9d0b17e14b55.png)

**Comment by KevCui** [comment]
Hi @ricky16x, could you please let me know the anime title in your screenshot? I can quickly check if the source is missing on the server.

**Comment by KevCui** [comment]
Hey @ricky16x, since there was no reply coming back from you, I assume this fix has been resolved? 

I'm closing this issue for now. If the issue still occurs, please tell me the anime title. I will reopen this issue ticket and quickly take a look.
