### ISSUE TITLE
[WARNING] Anime name not found!

### ISSUE THREAD

**Issue by Dwight123-crypto** [KevCui/animepahe-dl#65]
Hi @KevCui this two anime's can't be found...
![image](https://user-images.githubusercontent.com/62493728/168452189-5c03d0a8-9a92-4f7d-9cf1-fa4c33c6368b.png)
![image](https://user-images.githubusercontent.com/62493728/168452196-4da08844-9682-4b02-8be6-4638bed3601e.png)
![image](https://user-images.githubusercontent.com/62493728/168452202-d5612f25-ff61-4a27-b55a-73c8ae8f6e84.png)

**Comment by KevCui** [comment]
Hey @Dwight123-crypto, the anime slug/uuid is changing frequently on the server. You can run `./animepahe-dl.sh` once and get the latest slug uuid in `./anime.list`.

**Comment by Dwight123-crypto** [comment]
Yep working now
![image](https://user-images.githubusercontent.com/62493728/168464717-dbb03928-9f43-4056-a4b6-55d8c54fe2aa.png)

Thanks again man!
