### ISSUE TITLE
scrip is broke

### ISSUE THREAD

**Issue by falkpaulfabian2004** [KevCui/animepahe-dl#67]
this script give me this error out!

animepahe-dl.sh: line 292: syntax error near unexpected token `<'

**Comment by KevCui** [comment]
Hey @falkpaulfabian2004, did you run the script as `sh` or `bash`? The script should work with `bash`, not `sh`. If you are using `bash`, could you please check the version `bash --version` if it's the latest?

**Comment by KevCui** [comment]
Hey @falkpaulfabian2004, I'm closing this issue since there is no further reply from your side. I assume everything went well? If you are still having the same issue, please leave comments or feel free to open new issue with more details.
