### ISSUE TITLE
No audio on other anime

### ISSUE THREAD

**Issue by JomarAggabao** [KevCui/animepahe-dl#69]
No audio on One Piece. I tried to download other anime and it has audio, but when it comes to one piece there's no audio Sir. Please fix it Sir. I love your script

**Comment by KevCui** [comment]
Hey @JomarAggabao, did you check the same episode on the animepahe site directly? Maybe the media/video itself doesn't have audio?

**Comment by JomarAggabao** [comment]
Yes Sir, i played it on their site and the audio is fine. Did you try it ?

**Comment by KevCui** [comment]
Hey @JomarAggabao, ok please send me the anime name and episode number, or simply the link. I can quickly check.

**Comment by KevCui** [comment]
Hey @JomarAggabao, I tried some episodes of One Piece and audio works well for me. I'm closing this issue since there is no further information from your side. I hope everything went well for you in the end. If not, please let know me the episode number, I can then quickly check.
