### ISSUE TITLE
Content Error

### ISSUE THREAD

**Issue by joseflewis** [KevCui/animepahe-dl#70]
I downloaded many anime series using threads below 50 and once I tried to watch them, apparently they had video lags with parts getting an audio cut and I compared one episode downloaded by this script and one downloaded manually through site and the errors of the video did not show on the one that was downloaded manually, just a suggestion but can you not make a command that will show the link to download the episode so that we can use our own external download manager like IDM? if not then please help

**Comment by KevCui** [comment]
Hey @joseflewis, you could use flag `-l` to get the link without downloading, check README.md file for more details.
