### ISSUE TITLE
Download Link Not Working

### ISSUE THREAD

**Issue by joseflewis** [KevCui/animepahe-dl#71]
The m3ua link that the flag -l gives does not work, I tried putting https://eu-041.files.nextcdn.org/stream/08/365548b2a43671a1591a10a073ca17a56aa466cc276423cb22ff206203e1eaed/uwu.m3u8 in idm and it did not work, only an error occured probably because it's a stream link. What to do?

**Comment by KevCui** [comment]
Hey @joseflewis, I don't know how idm works. In general, you need to set the referrer header in order to use the link. For example:

```
mpv --http-header-fields="Referer: https://kwik.cx/" <m3u8_link>
```
