### ISSUE TITLE
Error in the pull function.[tls @ 000001cc1a676700] IO error: Error number -10054 occurred

### ISSUE THREAD

**Issue by prometheus209** [KevCui/animepahe-dl#75]
hello devs everytime i try to download anything I always get this error and the download stops. it downloads about 40-50 MB then it just stops entirely and gives me this error

![image](https://user-images.githubusercontent.com/112138523/186794844-84644ab8-2764-4398-9a10-651f52c63030.png)

**Comment by prometheus209** [comment]
when i was working with my vpn I accidentally tried downloading without turning it off and it seems to have worked does that mean the problem is with my isp or is it something in my router settings, FYI: i had just changed my isp and it used to work before.

**Comment by KevCui** [comment]
Hey @prometheus209, I don't think the issue you are facing is caused by the script. I'd guess it's some kind of network issue. 

To know more about where this error is coming from, you could try to run the script with `-d` flag and check the debug logs.
