### ISSUE TITLE
Parallel jobs to download is not working

### ISSUE THREAD

**Issue by savanchhayani** [KevCui/animepahe-dl#77]
Hi,

I am trying to download episodes with parallel jobs, but I am facing the below error every time. Is there any solution available?

#### Error: 
`./Naruto/4.mp4: No such file or directory`

<img width="539" alt="Screenshot 2022-09-22 at 10 20 03 PM" src="https://user-images.githubusercontent.com/32090577/191806312-5f130723-8487-4e3f-869e-81e8a4cd01e4.png">

**Comment by KevCui** [comment]
Hey @savanchhayani, from the screenshot, it looks like `realpath` command was not found on your machine. This command binary should be included in GNU coreutils, please install it and it should work without error.
