### ISSUE TITLE
Hey @mish20011, as npm audit suggested, run `npm audit fix` will fix the reported vulns in the dependencies.

### ISSUE THREAD

**Issue by mish20011** [KevCui/animepahe-dl#79]
Hey @mish20011, as npm audit suggested, run `npm audit fix` will fix the reported vulns in the dependencies.

_Originally posted by @KevCui in https://github.com/KevCui/animepahe-dl/issues/78#issuecomment-1259930381_

here is what it said after I did it

Leahsim@DESKTOP-GK31TCE MINGW64 ~/Desktop/animepahe-dl-master
$ npm audit fix

up to date, audited 121 packages in 8s

20 packages are looking for funding
  run `npm fund` for details

# npm audit report

jsdom  <=16.4.0
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98
fix available via `npm audit fix`
node_modules/jsdom

tough-cookie  <=2.3.2
Severity: high
Regular Expression Denial of Service in tough-cookie - https://github.com/advisories/GHSA-g7q5-pjjr-gqvp
ReDoS via long string of semicolons in tough-cookie - https://github.com/advisories/GHSA-qhv9-728r-6jqg
No fix available
node_modules/tough-cookie-filestore/node_modules/tough-cookie
  tough-cookie-filestore  *
  Depends on vulnerable versions of tough-cookie
  node_modules/tough-cookie-filestore

xmlhttprequest  <1.7.0
Severity: high
Arbitrary Code Injection - https://github.com/advisories/GHSA-h4j5-c7cj-74xg
No fix available
node_modules/xmlhttprequest
  jq  *
  Depends on vulnerable versions of jsdom
  Depends on vulnerable versions of xmlhttprequest
  node_modules/jq

5 vulnerabilities (1 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Leahsim@DESKTOP-GK31TCE MINGW64 ~/Desktop/animepahe-dl-master
$

**Comment by mish20011** [comment]
I followed it up by npm fund

Leahsim@DESKTOP-GK31TCE MINGW64 ~/Desktop/animepahe-dl-master
$ npm fund
user
├─┬ https://github.com/cheeriojs/cheerio?sponsor=1
│ │ └── cheerio@1.0.0-rc.12
│ ├── https://github.com/sponsors/fb55
│ │   └── cheerio-select@2.1.0, css-select@5.1.0, css-what@6.1.0, domelementtype@2.3.0
│ ├─┬ https://github.com/cheeriojs/dom-serializer?sponsor=1
│ │ │ └── dom-serializer@2.0.0
│ │ └── https://github.com/fb55/entities?sponsor=1
│ │     └── entities@4.4.0
│ ├── https://github.com/fb55/domhandler?sponsor=1
│ │   └── domhandler@5.0.3
│ ├── https://github.com/fb55/domutils?sponsor=1
│ │   └── domutils@3.0.1
│ ├── https://github.com/fb55/htmlparser2?sponsor=1
│ │   └── htmlparser2@8.0.1
│ └── https://github.com/inikulin/parse5?sponsor=1
│     └── parse5@7.1.1, parse5-htmlparser2-tree-adapter@7.0.0
├── https://github.com/sponsors/feross
│   └── base64-js@1.5.1, safe-buffer@5.2.1
├── https://github.com/sponsors/isaacs
│   └── rimraf@3.0.2, glob@7.2.3
├── https://github.com/sponsors/epoberezkin
│   └── ajv@6.12.6
└─┬ https://github.com/chalk/wrap-ansi?sponsor=1
  │ └── wrap-ansi@7.0.0
  └── https://github.com/chalk/ansi-styles?sponsor=1
      └── ansi-styles@4.3.0


Leahsim@DESKTOP-GK31TCE MINGW64 ~/Desktop/animepahe-dl-master
$

**Comment by mish20011** [comment]
please help, its still not working

**Comment by KevCui** [comment]
Hey @mish20011, this project doesn't depend on any npm modules. The reported issue is irrelevant.

**Comment by mish20011** [comment]
> Hey @mish20011, this project doesn't depend on any npm modules. The reported issue is irrelevant.

you close every issue instantly without even giving proper explanation, what an ass, at least give me a reason, I did what you said but nothing changed, you didn't provide an alternative, what the fuck man

**Comment by KevCui** [comment]
Hey @mish20011, as I explained: `this project doesn't depend on any npm modules. The reported issue is irrelevant.` It seems you still don't understand, allow me provide more details: Please check the dependency section in the project README.md, to use this script doesn't require any npm modules. Hence, the issue you reported regarding those npm modules is not related to this project.

I closed this issue because there won't be any further action from my side. It doesn't mean I refuse the further communication. If you are still unclear about my reply or you have further discovery, you could continue leave comments in this issue and I will try to clarify as soon as I can.
