### ISSUE TITLE
How to use this? & ([ERROR] Missing video list!)

### ISSUE THREAD

**Issue by uali6981** [KevCui/animepahe-dl#8]
Please help me in "How to use this code"?

Thanks

**Comment by KevCui** [comment]
After clone/download this repository, install dependencies listed here: https://github.com/KevCui/animepahe-dl#dependency. Then run script `animepahe-dl.sh` following the examples: https://github.com/KevCui/animepahe-dl#how-to-use

**Comment by uali6981** [comment]
Thanks for this.
After installing I got this error.

![image](https://user-images.githubusercontent.com/56256581/100834827-66d27100-348e-11eb-837d-87e48557b8d6.png)

**Comment by KevCui** [comment]
@uali6981 Weird. The anime video link did work for me. Could you please post the output of this command `bash -x ./animepahe-dl.sh -s a30d23f9-19e1-a07f-93c0-1612559c6f46 -e 1`? It will help me to debug this issue. Thanks

**Comment by uali6981** [comment]
`bash -x ./animepahe-dl.sh -s a30d23f9-19e1-a07f-93c0-1612559c6f46 -e 1`

+ set -e
+ set -u
+ [[ ./animepahe-dl.sh == \.\/\a\n\i\m\e\p\a\h\e\-\d\l\.\s\h ]]   
+ main -s a30d23f9-19e1-a07f-93c0-1612559c6f46 -e 1
+ set_args -s a30d23f9-19e1-a07f-93c0-1612559c6f46 -e 1
+ expr '-s a30d23f9-19e1-a07f-93c0-1612559c6f46 -e 1' : '.*--help'
+ getopts :hla:s:e: opt
+ case $opt in
+ _ANIME_SLUG=a30d23f9-19e1-a07f-93c0-1612559c6f46
+ getopts :hla:s:e: opt
+ case $opt in
+ _ANIME_EPISODE=1
+ getopts :hla:s:e: opt
+ set_var
++ command -v curl
+ _CURL=/mingw64/bin/curl
++ command -v jq
+ _JQ=/c/ProgramData/chocolatey/bin/jq
++ command -v pup
+ _PUP=/c/Users/H-Usman-Ali/AppData/Roaming/youtube-dl/ffmpeg/bin/pup
++ command -v fzf
+ _FZF=/c/ProgramData/chocolatey/bin/fzf
++ command -v node
+ _NODE='/c/Program Files/nodejs/node'
++ command -v ffmpeg
+ _FFMPEG=/c/Users/H-Usman-Ali/AppData/Roaming/youtube-dl/ffmpeg/bin/ffmpeg
+ _HOST=https://animepahe.com
+ _ANIME_URL=https://animepahe.com/anime
+ _API_URL=https://animepahe.com/api
+ _REFERER_URL=https://kwik.cx/
+++ realpath ./animepahe-dl.sh
++ dirname /d/Projects/animepahe-dl/animepahe-dl.sh
+ _SCRIPT_PATH=/d/Projects/animepahe-dl
+ _ANIME_LIST_FILE=/d/Projects/animepahe-dl/anime.list
+ _SOURCE_FILE=.source.json
+ [[ -n '' ]]
+ [[ -z a30d23f9-19e1-a07f-93c0-1612559c6f46 ]]
+ [[ a30d23f9-19e1-a07f-93c0-1612559c6f46 == '' ]]
++ sort -u /d/Projects/animepahe-dl/anime.list
++ grep a30d23f9-19e1-a07f-93c0-1612559c6f46
++ awk -F '] ' '{print $2}'++ sed -E 's/\//_/g'

+ _ANIME_NAME='Noragami OVA
Noragami OVA'
+ [[ Noragami OVA
Noragami OVA == '' ]]
+ download_source
+ local id d p n
+ mkdir -p '/d/Projects/animepahe-dl/Noragami OVA
Noragami OVA'
++ get_anime_id a30d23f9-19e1-a07f-93c0-1612559c6f46
++ /mingw64/bin/curl -sS https://animepahe.com/anime/a30d23f9-19e1-a07f-93c0-1612559c6f46
++ grep getJSON
++ sed -E 's/.*id=//'
++ awk -F '&' '{print $1}'
+ id=842
++ get_episode_list 842 1
++ /mingw64/bin/curl -sS 'https://animepahe.com/api?m=release&id=842&sort=episode_asc&page=1'
+ d='{"total":2,"per_page":30,"current_page":1,"last_page":1,"next_page_url":null,"prev_page_url":null,"from":1,"to":2,"data":[{"id":30,"anime_id":842,"episode":1,"episode2":0,"edition":"","title":"","snapshot":"","disc":"DVD","duration":"00:23:59","session":"be8872eae5f9c18f7304de904796d3b05d4ae980709c773639db967295b662fe","filler":0,"created_at":"2016-03-11 20:49:48"},{"id":31,"anime_id":842,"episode":2,"episode2":0,"edition":"","title":"","snapshot":"","disc":"DVD","duration":"00:23:59","session":"1e83c684a1884df8aa9f1663a9a6294073eb420c785aee913e46e84ae4f89183","filler":0,"created_at":"2016-03-11 20:54:20"}]}'
++ /c/ProgramData/chocolatey/bin/jq -r .last_page
+ p=1
+ [[ 1 -gt 1 ]]
+ echo '{"total":2,"per_page":30,"current_page":1,"last_page":1,"next_page_url":null,"prev_page_url":null,"from":1,"to":2,"data":[{"id":30,"anime_id":842,"episode":1,"episode2":0,"edition":"","title":"","snapshot":"","disc":"DVD","duration":"00:23:59","session":"be8872eae5f9c18f7304de904796d3b05d4ae980709c773639db967295b662fe","filler":0,"created_at":"2016-03-11 20:49:48"},{"id":31,"anime_id":842,"episode":2,"episode2":0,"edition":"","title":"","snapshot":"","disc":"DVD","duration":"00:23:59","session":"1e83c684a1884df8aa9f1663a9a6294073eb420c785aee913e46e84ae4f89183","filler":0,"created_at":"2016-03-11 20:54:20"}]}'
+ [[ -z 1 ]]
+ download_episodes 1
+ local origel el uniqel
+ origel=()
+ [[ 1 == *\,* ]]
+ origel+=("$1")
+ el=()
+ for i in "${origel[@]}"
+ [[ 1 == *\-* ]]
+ el+=("$i")
+ IFS=' '
+ read -ra uniqel
++ printf '%s\n' 1
++ sort -n -u
++ tr '\n' ' '
+ [[ 1 == 0 ]]
+ for e in "${uniqel[@]}"
+ download_episode 1
+ local l pl
++ get_episode_link 1
++ local i s
+++ /c/ProgramData/chocolatey/bin/jq -r '.data[] | select((.episode | tonumber) == ($num | tonumber)) | .anime_id' --arg num 1
++ i=842
+++ /c/ProgramData/chocolatey/bin/jq -r '.data[] | select((.episode | tonumber) == ($num | tonumber)) | .session' --arg num 1     
++ s=be8872eae5f9c18f7304de904796d3b05d4ae980709c773639db967295b662fe
++ [[ 842 == '' ]]
++ /mingw64/bin/curl -sS 'https://animepahe.com/api?m=embed&id=842&session=be8872eae5f9c18f7304de904796d3b05d4ae980709c773639db967295b662fe&p=kwik'
++ /c/ProgramData/chocolatey/bin/jq -r '.data[][].kwik'
++ tail -1
+ l=https://kwik.cx/e/pyWU5cwdbcM2
+ [[ https://kwik.cx/e/pyWU5cwdbcM2 != *\/* ]]
++ get_playlist https://kwik.cx/e/pyWU5cwdbcM2
++ local s l
+++ /mingw64/bin/curl -sS -H 'Referer: https://kwik.cx/' https://kwik.cx/e/pyWU5cwdbcM2
+++ grep '<script>'
+++ sed -E 's/<script>//'
++ s='eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'\'''\'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!'\'''\''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\''\\w+'\''};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\''\\b'\''+e(c)+'\''\\b'\'','\''g'\''),k[c])}}return p}('\''f $7={H:a(2){4 
B(9.7.h(y z("(?:(?:^|.*;)\\\\s*"+d(2).h(/[\\-\\.\\+\\*]/g,"\\\\$&")+"\\\\s*\\\\=\\\\s*([^;]*).*$)|^.*$"),"$1"))||G},E:a(2,q,3,6,5,t){k(!2||/^(?:8|r\\-v|o|m|p)$/i.D(2)){4 w}f b="";k(3){F(3.J){j K:b=3===P?"; 8=O, I N Q M:u:u A":"; r-v="+3;n;j L:b="; 8="+3;n;j S:b="; 8="+3.Z();n}}9.7=d(2)+"="+d(q)+b+(5?"; m="+5:"")+(6?"; o="+6:"")+(t?"; p":"");4 x},Y:a(2,6,5){k(!2||!11.C(2)){4 w}9.7=d(2)+"=; 8=12, R 10 W l:l:l A"+(5?"; m="+5:"")+(6?"; o="+6:"");4 x},C:a(2){4(y z("(?:^|;\\\\s*)"+d(2).h(/[\\-\\.\\+\\*]/g,"\\\\$&")+"\\\\s*\\\\=")).D(9.7)},X:a(){f c=9.7.h(/((?:^|\\s*;)[^\\=]+)(?=;|$)|^\\s*|\\s*(?:\\=[^;]*)?(?:\\1|$)/g,"").T(/\\s*(?:\\=[^;]*)?;\\s*/)Keys|encodeURIComponent|nIdx|var||replace||case|if|00|domain|break|path|secure|sValue|max||bSecure|59|age|false|true|new|RegExp|GMT|decodeURIComponent|hasItem|test|setItem|switch|null|getItem|31|constructor|Number|String|23|Dec|Fri|Infinity|9999|01|Date|split|for|length|1970|keys|removeItem|toUTCString|Jan|this|Thu'\''.split('\''|'\''),0,{}));eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'\'''\'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!'\'''\''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\''\\w+'\''};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\''\\b'\''+e(c)+'\''\\b'\'','\''g'\''),k[c])}}return p}('\''i m=\'\''1s://F-K-L.C.N/M/Q/X/Z.O\'\'';i d=Y.W(\'\''d\'\'');i 0=r 
V(d,{\'\''U\'\'':{\'\''T\'\'':s},\'\''S\'\'':\'\''16:9\'\'',\'\''R\'\'':5,\'\''P\'\'':{\'\''J\'\'':\'\''I\'\''},H:[\'\''7-G\'\'',\'\''7\'\'',\'\''E\'\'',\'\''D-a\'\'',\'\''10\'\'',\'\''B\'\'',\'\''12\'\'',\'\''13\'\'',\'\''1r\'\'',\'\''1q\'\'',\'\''u\'\''],\'\''u\'\'':{\'\''1p\'\'':s}});3(!q.1o()){d.1n=m}t{h o={1m:1l};i b=r q(o);b.11(m);b.1k(d);f.b=b}0.4("1j",8=>{f.1i.1h.1g("1f")});0.1e=1;k x(c,l,n){3(c.p){c.p(l,n,1d)}t 3(c.v){c.v(\'\''4\'\''+l,n)}}h 6=k(j){f.1c.1b(j,\'\''*\'\'')};x(f,\'\''j\'\'',k(e){h 2=e.2;3(2===\'\''7\'\'')0.7();3(2===\'\''g\'\'')0.g();3(2===\'\''A\'\'')0.A();3(2.1a(\'\''a\'\'')){h a=19(2.18(\'\''-\'\'')[1]);17.15(a);0.y=a}});0.4(\'\''z\'\'',8=>{6(\'\''z\'\'')});0.4(\'\''7\'\'',8=>{6(\'\''7\'\'')});0.4(\'\''g\'\'',8=>{6(\'\''g\'\'')});0.4(\'\''14\'\'',8=>{6(0.y)});0.4(\'\''w\'\'',8=>{6(\'\''w\'\'')});'\'',62,91,'\''player||data|if|on||sendMessage|play|event||time|hls|element|video||window|pause|var|const|message|function|eventName|source|eventHandler|config|addEventListener|Hls|new|true|else|fullscreen|attachEvent|ended|bindEvent|currentTime|ready|stop|volume|nextstream|current|progress|files|large|controls|kwik|key|na|a3|stream|org|m3u8|storage|0001|seekTime|ratio|global|keyboard|Plyr|querySelector|3d1439471891241527533efd412150dd6ed515c6b9d4b8b6aa0e37f8a4252daa|document|uwu|mute|loadSource|captions|settings|timeupdate|log||console|split|parseInt|includes|postMessage|parent|false|speed|landscape|lock|orientation|screen|enterfullscreen|attachMedia|90|maxBufferLength|src|isSupported|iosNative|airplay|pip|https'\''.split('\''|'\''),0,{}))'
+++ /c/Program Files/nodejs/node -e 'eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'\'''\'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!'\'''\''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\''\\w+'\''};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\''\\b'\''+e(c)+'\''\\b'\'','\''g'\''),k[c])}}return p}('\''f $7={H:a(2){4 B(9.7.h(y z("(?:(?:^|.*;)\\\\s*"+d(2).h(/[\\-\\.\\+\\*]/g,"\\\\$&")+"\\\\s*\\\\=\\\\s*([^;]*).*$)|^.*$"),"$1"))||G},E:a(2,q,3,6,5,t){k(!2||/^(?:8|r\\-v|o|m|p)$/i.D(2)){4 w}f b="";k(3){F(3.J){j K:b=3===P?"; 8=O, I N Q M:u:u A":"; 
r-v="+3;n;j L:b="; 8="+3;n;j S:b="; 8="+3.Z();n}}9.7=d(2)+"="+d(q)+b+(5?"; m="+5:"")+(6?"; o="+6:"")+(t?"; p":"");4 x},Y:a(2,6,5){k(!2||!11.C(2)){4 w}9.7=d(2)+"=; 8=12, R 10 W l:l:l A"+(5?"; m="+5:"")+(6?"; o="+6:"");4 x},C:a(2){4(y z("(?:^|;\\\\s*)"+d(2).h(/[\\-\\.\\+\\*]/g,"\\\\$&")+"\\\\s*\\\\=")).D(9.7)},X:a(){f c=9.7.h(/((?:^|\\s*;)[^\\=]+)(?=;|$)|^\\s*|\\s*(?:\\=[^;]*)?(?:\\1|$)/g,"").T(/\\s*(?:\\=[^;]*)?;\\s*/);U(f e=0;e<c.V;e++){c[e]=B(c[e])}4 c}};'\'',62,65,'\''||sKey|vEnd|return|sDomain|sPath|cookie|expires|document|function|sExpires|aKeys|encodeURIComponent|nIdx|var||replace||case|if|00|domain|break|path|secure|sValue|max||bSecure|59|age|false|true|new|RegExp|GMT|decodeURIComponent|hasItem|test|setItem|switch|null|getItem|31|constructor|Number|String|23|Dec|Fri|Infinity|9999|01|Date|split|for|length|1970|keys|removeItem|toUTCString|Jan|this|Thu'\''.split('\''|'\''),0,{}));eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'\'''\'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!'\'''\''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\''\\w+'\''};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\''\\b'\''+e(c)+'\''\\b'\'','\''g'\''),k[c])}}return p}('\''i m=\'\''1s://F-K-L.C.N/M/Q/X/Z.O\'\'';i d=Y.W(\'\''d\'\'');i 0=r V(d,{\'\''U\'\'':{\'\''T\'\'':s},\'\''S\'\'':\'\''16:9\'\'',\'\''R\'\'':5,\'\''P\'\'':{\'\''J\'\'':\'\''I\'\''},H:[\'\''7-G\'\'',\'\''7\'\'',\'\''E\'\'',\'\''D-a\'\'',\'\''10\'\'',\'\''B\'\'',\'\''12\'\'',\'\''13\'\'',\'\''1r\'\'',\'\''1q\'\'',\'\''u\'\''],\'\''u\'\'':{\'\''1p\'\'':s}});3(!q.1o()){d.1n=m}t{h o={1m:1l};i b=r q(o);b.11(m);b.1k(d);f.b=b}0.4("1j",8=>{f.1i.1h.1g("1f")});0.1e=1;k x(c,l,n){3(c.p){c.p(l,n,1d)}t 3(c.v){c.v(\'\''4\'\''+l,n)}}h 6=k(j){f.1c.1b(j,\'\''*\'\'')};x(f,\'\''j\'\'',k(e){h 2=e.2;3(2===\'\''7\'\'')0.7();3(2===\'\''g\'\'')0.g();3(2===\'\''A\'\'')0.A();3(2.1a(\'\''a\'\'')){h a=19(2.18(\'\''-\'\'')[1]);17.15(a);0.y=a}});0.4(\'\''z\'\'',8=>{6(\'\''z\'\'')});0.4(\'\''7\'\'',8=>{6(\'\''7\'\'')});0.4(\'\''g\'\'',8=>{6(\'\''g\'\'')});0.4(\'\''14\'\'',8=>{6(0.y)});0.4(\'\''w\'\'',8=>{6(\'\''w\'\'')});'\'',62,91,'\''player||data|if|on||sendMessage|play|event||time|hls|element|video||window|pause|var|const|message|function|eventName|source|eventHandler|config|addEventListener|Hls|new|true|else|fullscreen|attachEvent|ended|bindEvent|currentTime|ready|stop|volume|nextstream|current|progress|files|large|controls|kwik|key|na|a3|stream|org|m3u8|storage|0001|seekTime|ratio|global|keyboard|Plyr|querySelector|3d1439471891241527533efd412150dd6ed515c6b9d4b8b6aa0e37f8a4252daa|document|uwu|mute|loadSource|captions|settings|timeupdate|log||console|split|parseInt|includes|postMessage|parent|false|speed|landscape|lock|orientation|screen|enterfullscreen|attachMedia|90|maxBufferLength|src|isSupported|iosNative|airplay|pip|https'\''.split('\''|'\''),0,{}))'
+++ grep source=
+++ sed -E 's/.m3u8'\'';.*/.m3u8/'
+++ sed -E 's/.*const source='\''//'
++ l=
++ echo ''
+ pl=
+ [[ -z '' ]]
+ print_error 'Missing video list!'
+ printf '%b\n' '\033[31m[ERROR]\033[0m Missing video list!'
[ERROR] Missing video list!
+ exit `

**Comment by KevCui** [comment]
@uali6981 May I ask which `node` version do you have? `node -v`

**Comment by uali6981** [comment]
![image](https://user-images.githubusercontent.com/56256581/100861192-4d8feb80-34b3-11eb-975b-54526e08d8e7.png)

**Comment by KevCui** [comment]
@uali6981 The node version does look good. I don't know why deobfuscation is not working... Anyway, I tried to add another function to use `js-beautify` as fallback in the latest commit.

Could you please try it again? First, download again this repository, then install js-beautify `pip install jsbeautifier` and run `./animepahe-dl.sh -s a30d23f9-19e1-a07f-93c0-1612559c6f46 -e 1`

**Comment by uali6981** [comment]
![image](https://user-images.githubusercontent.com/56256581/100872924-5f2dbf00-34c4-11eb-842f-6f0986930298.png)


![image](https://user-images.githubusercontent.com/56256581/100872965-7076cb80-34c4-11eb-8e4b-9bced067aa42.png)

**Comment by KevCui** [comment]
@uali6981 I think I may get the problem. It's because the empty space in command path `c/Program<space>`. I hope the latest commit fix it, please take a look :pray:

**Comment by uali6981** [comment]
![image](https://user-images.githubusercontent.com/56256581/100880097-27c41000-34ce-11eb-8f36-09310d846897.png)

**Comment by KevCui** [comment]
@uali6981 The full path should be `/c/program files/...`, since there is an empty space in the path, it causes the issue.

This issue should be fixed in the latest commit. Please clone the repository and try again. 🙏

**Comment by uali6981** [comment]
again

![image](https://user-images.githubusercontent.com/56256581/100893167-e38c3c00-34dc-11eb-8572-989a4e48b49c.png)

**Comment by KevCui** [comment]
@uali6981 oh sorry about that... We're getting closer to solve this problem 🙂. Could you please edit the script `animepahe.sh` line 171, put quotes around $_JSBEAUTIFY, like`"$_JSBEAUTIFY"`. If it works, I'll then commit it later.

**Comment by uali6981** [comment]
thanks working now

and is there any way for only getting download url link of eps?

**Comment by KevCui** [comment]
@uali6981 great!

Using option `-l` will show the URL for m3u8 file without downloading video.
