### ISSUE TITLE
Default downloads english dub

### ISSUE THREAD

**Issue by Baburuti** [KevCui/animepahe-dl#83]
Hi as the title says the script just downloads all anime in english dub without specifying it, checked with different anime but all of them have this issue 
Tried specifying it to japanese with jp and jap but neither of them are working and just rolls back to english dub as default

**Comment by KevCui** [comment]
Hey @Baburuti, try `-o jpn`. If it's still not working, please let me know the anime title, I'll quickly check.

**Comment by Baburuti** [comment]
> Hey @Baburuti, try `-o jpn`. If it's still not working, please let me know the anime title, I'll quickly check.

The `-o jpn` worked.
Although is there any chance i could set it to download japanese by default? Didnt had this issue before downloading an update

**Comment by KevCui** [comment]
Hey @Baburuti, the "default" audio language depends on the server side. If no language is specified while running the script, the script simply takes the first matched resource to download.
