### ISSUE TITLE
synthax error

### ISSUE THREAD

**Issue by sebatrino** [KevCui/animepahe-dl#84]
Hi,
 could anyone please hlep me with using this downloader?

I'm totaly lost in this pantheon thing. I've managed to install it and run it. I even managed to store this app as .py file and to load it into module.
However, when I start it by 'run' I get all sorts of 'syntax warnings' warnings like the one attached.

What am I doing wrong here?

Thanks for any valuable advice.

![animepahe downloader error 1](https://user-images.githubusercontent.com/125198538/218315967-8731df2f-a120-4756-8223-279b5a0f9ffc.jpg)

S

**Comment by KevCui** [comment]
Hey @sebatrino, it' is a Shell script in this project, not Python. Please check the README.md file for dependencies and its usage. Let me know if you need help. Take care.

**Comment by sebatrino** [comment]
Hi Kevin,

and thanks for your explanation.

I'm a newbie in using Python and thought Python is used for this script.
I tried to run the .yp file itself and only get an open window that closes
in a milisecond without any further action.

What am I doing wrong here? I'm using Brave 64bit.

Is there any other script/app that runs through Python or as a
self-standing app like IMD, which I could use for animepahe download of
full seasons?

Best,
S

**Comment by KevCui** [comment]
Hey @sebatrino, you could search for "bash script 101" or "bash script basic" to get some materials that will help you understand how the bash/shell script works. Regarding the Python app like IMD, unfortunately, I don't know any. Hope you will find a good solution soon. Cheers!

**Comment by sebatrino** [comment]
Hi,

I've managed to set up everything and it seems to work.
Is there a way to set up a sound notification to hear/know when all
downloads are finished?

How does one set up multiple series to be downloaded one after another the
way this works with torrents, or IDM?

For instance, first you choose Naruto xx episodes, then Gundam, Detective
Conan... and so on.

This way one can leave the PC to do its job ofr a loner period, without
checking up every half an houir if the job is done.

Is there a way to make a list for all chosen downloadable links to be used
in IDM? I've tried the list this app makes and IDM cannot download it, like
'forbidden access?'

Best,
S

**Comment by KevCui** [comment]
Hey @sebatrino,

You may use other command to send sound notification. For example, use `mpv` to open a sound file, etc...

Regards forbidden access, you need to add header `Referer: https://kwik.cx/` in order to use download link. You can find details in README.md.

**Comment by sebatrino** [comment]
Hi KevCui,

thanks for your suggestions.

Is there a way to set up a job, combine multiple series into a batch
download, one after another, so that one can leave PC to work through the
night?

Best,
S

**Comment by KevCui** [comment]
Hey @sebatrino, you may put multiple commands in a sh file and run it. Using `-s` and `-e` flag in the script can avoid interactions. Give it a try.
