### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by NRostheGuy** [KevCui/animepahe-dl#85]
When it tries to download the episodes, it fails saying 'eu-10.cache.nextcdn.org port 443 after 5007 ms' or something.

**Comment by KevCui** [comment]
Hey @NRostheGuy, did you try to view the same episode online to see if it works? If you are able to watch it online, but still have issue with the script to download. Please let me know which anime and episode you have the problem to download. I will take a look then.

**Comment by KevCui** [comment]
If you were using the parallel mode with `-t`, you may see those types of message due to the network issue. But it is not a problem, the script has retry functionality and will keep downloading episode.

After the script finishes the execution, you can check the downloaded episode. If the script is exited in the middle of the execution due to error, please try run again with `-d` to enable debug logs. Paste the logs here and I will check. Thanks!

**Comment by NRostheGuy** [comment]
It just stops executing the script after getting the error. I have experienced it failing and retrying before, but this is not that. Rather than the ping error, it seems to be showing this now..

![image](https://user-images.githubusercontent.com/128509897/227202819-50f26507-8df5-4bbe-b006-e0bbf326a0b2.png)

[Logs.txt](https://github.com/KevCui/animepahe-dl/files/11050796/Logs.txt)

**Comment by lord8266** [comment]
That is the timeout error, maybe try with multiple threads 
```
./animepahe-dl.sh -t 50
```

**Comment by NRostheGuy** [comment]
> That is the timeout error, maybe try with multiple threads
> 
> ```
> ./animepahe-dl.sh -t 50
> ```

Using threads gets the error I mentioned in the beginning of the post.

**Comment by KevCui** [comment]
Hey @NRostheGuy, I' have the feeling it's something related to the network or the server side. Did normal download without `-t` work for you?

**Comment by NRostheGuy** [comment]
It actually seems to be working now both with and without threads(it displayed errors on both before), probably server issues then,yeah.

**Comment by KevCui** [comment]
Hey @NRostheGuy, glad to hear that it's working for you now. I'm closing this issue then. Cheers.

**Comment by NRostheGuy** [comment]
> Hey @NRostheGuy, glad to hear that it's working for you now. I'm closing this issue then. Cheers.

My apologies, but after some testing I think I've figured out the problem - recent uploads(no idea how recent, but it's the case for anime I've seen uploaded/reuploaded onto the site in the recent past) display error number -138 as seen in the attachment on my second message, regardless of threads. It's been working perfectly for other titles.

**Comment by KevCui** [comment]
Hi @NRostheGuy, could you share name and episode of the anime that causes download issues? I can quickly check.

**Comment by NRostheGuy** [comment]
@KevCui You could try something like Mob Psycho 100 III or Yofukashi no Uta. Also, for these anime it outright skips the Select Video Resolution check that comes before the episode number(in the event that the resolution is specified).

**Comment by lord8266** [comment]
@NRostheGuy I can download both, can you view the episodes on animepahe.com though?

**Comment by NRostheGuy** [comment]
@lord8266 No, the stuff that can't be downloaded doesn't even work on the site. I can download them individually from the site itself tho, which is a pain.

**Comment by KevCui** [comment]
Hey @NRostheGuy, if you're not able to view those anime on the site, it seems your access/IP has been restricted by the server/backend. I'm afraid it's not an issue we could solve from the script side, unfortunately.
