### ISSUE TITLE
When dowloading using batch downloader chapters are missing.

### ISSUE THREAD

**Issue by xHaruke** [KevCui/animepahe-dl#87]
There are chapters in the anime for intro and outro which are present when manually downloading but missing when using batch downloader.

**Comment by KevCui** [comment]
Hey @xHaruke, I didn't notice this at all, interesting. Could you let me know which anime which episode you downloaded? I can quickly check if this can be implemented in the script or not.

**Comment by KevCui** [comment]
Hey @xHaruke, the downloaded file from the site is one mp4 file contains chapter metadata, that's why you saw it in mpv. The script downloads m3u8 playlist and segments, as the same as streaming, and there is no such metadata. The file sources are different. Sorry, cannot make it.
