### ISSUE TITLE
Error. While downloading 

### ISSUE THREAD

**Issue by Anas-Mughal** [KevCui/animepahe-dl#88]
./animepahe-dl.sh: line 294:  6270 Killed                  xargs -I {} -P "$(get_thread_number "$1")" bash -c 'url="{}"; file="${url##*/}.encrypted"; download_file "$url" "${op}/${file}"' < <(grep "^https" "$1")

[Process completed (signal 9) - press Enter]

**Comment by lord8266** [comment]
Which anime and episode?

**Comment by KevCui** [comment]
Hey @Anas-Mughal, following the question from @lord8266, are you able to download this episode using normal download mode without `-t`?

**Comment by Anas-Mughal** [comment]
> Hey @Anas-Mughal, following the question from @lord8266, are you able to download this episode using normal download mode without `-t`?

Yes

**Comment by KevCui** [comment]
@Anas-Mughal which anime and episode? I can quickly check it.

**Comment by Anas-Mughal** [comment]
> @Anas-Mughal which anime and episode? I can quickly check it.


Then I was downloading Parasyte. But now you can check by downloading Black Clover or Mob Psycho 100 but the error is same in downloading all anime.

**Comment by KevCui** [comment]
Hey @Anas-Mughal, I tried the mentioned amines and I don't see the error. It seems the error `[Process completed (signal 9) - press Enter]` related to termux on Android. If you are using termux to run the script, please try to use smaller number with `-t`, or search online for this error and you may find a solution to this termux error.

**Comment by Anas-Mughal** [comment]
> Hey @Anas-Mughal, I tried the mentioned amines and I don't see the error. It seems the error `[Process completed (signal 9) - press Enter]` related to termux on Android. If you are using termux to run the script, please try to use smaller number with `-t`, or search online for this error and you may find a solution to this termux error.

Do you know how I can fix this? Because earlier I used to download from Termux and this problem did not occur. And I also reduced the value of argument -t and the same problem occurs.

**Comment by KevCui** [comment]
@Anas-Mughal, I don't know how since I don't have this problem... Here is a googled result that looks like a solution: https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#how-to-disable-the-phantom-processes-killing. You can try to search `[Process completed (signal 9) - press Enter]` and find more results. Good luck!
