### ISSUE TITLE
[ FEATURE REQUEST ] Ability to specify video quality

### ISSUE THREAD

**Issue by Akianonymus** [KevCui/animepahe-dl#9]
Animepahe provides multiple quality for many videos. It would be helpful if one wants to download a specific quality.

If not available, should fallback to whatever available.

**Comment by KevCui** [comment]
Thanks for the idea. The selection of video resolution is implemented in https://github.com/KevCui/animepahe-dl/commit/b24c6cf39f3c24c48cc15d9e3c6856798f99793d, using  the option `-r`, like `-r 720`.

**Comment by Akianonymus** [comment]
It works, thank you for implementing this feature.

Also, if we don't give the slug, flags like -r or -e are ignored. Is this intented ?

**Comment by KevCui** [comment]
@Akianonymus The slug is not mandatory, `-r` and `-e` should work independently. Without `-s`, script will prompt the anime list to select. Then after the selection, `-r` and `-e` options will be applied.

Let me know if it's not working for you. Post your issue with details here or another issue ticket, I will then take a look.
