### ISSUE TITLE
when it fetches the list it does not fetch the slugs or names

### ISSUE THREAD

**Issue by goodwake** [KevCui/animepahe-dl#92]
the list file is 0kb and it shows me this error when i check it

**Comment by goodwake** [comment]
![image](https://github.com/KevCui/animepahe-dl/assets/90543174/c5093faa-53e5-430b-9b94-5c4fc32359cf)

**Comment by KevCui** [comment]
Hey @goodwake, try to use script with `-a` or `-s` flag, more details can be found in README.md. If it's still not working, please run debug mode with `-d` and share logs, I will take a look. Thanks!

**Comment by goodwake** [comment]
i tried both 
but ill try again

**Comment by goodwake** [comment]
![image](https://github.com/KevCui/animepahe-dl/assets/90543174/3a2eee40-2d5f-4d24-9f2d-6f91f19d1ea4)

**Comment by goodwake** [comment]
this was using the slug

**Comment by lord8266** [comment]
@goodwake use the latest code, nice trick @KevCui

**Comment by goodwake** [comment]
![image](https://github.com/KevCui/animepahe-dl/assets/90543174/9eca3559-62e7-4bed-a417-fefa0c88008b)

**Comment by goodwake** [comment]
> @goodwake use the latest code, nice trick @KevCui

ive tried re downloading it
 yesterday but ill try that again too

**Comment by lord8266** [comment]
yeah just ignore stupid prs like #94. Its written by idiots like me

**Comment by goodwake** [comment]
okay thanks ^^

**Comment by goodwake** [comment]
![image](https://github.com/KevCui/animepahe-dl/assets/90543174/64ca8f35-9745-4fb9-9c62-8e3796d07835)

**Comment by goodwake** [comment]
what did i goof up now

**Comment by goodwake** [comment]
okay thats weird it worked now
mb

**Comment by lord8266** [comment]
You need to add quotes around `*`, otherwise it will select all files in current directory
```
./animepahe-dl.sh -d -s fa302cb4-3ba9-4647-8356-da16407cc11d  -e '*' -r 720 -o jpn -t 45
```
