### ISSUE TITLE
jq: parse error

### ISSUE THREAD

**Issue by kraithus** [KevCui/animepahe-dl#93]
Worked fine 2 days ago but now when I run
`./animepahe-dl.sh -a 'anime name' -e 1-2  -t 30 -o jpn`
It outputs
```
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
```
See attached screenshot
![2023-11-05_05-58](https://github.com/KevCui/animepahe-dl/assets/89634435/f3a6d3c3-a0fe-4748-bf1a-1809fa77f191)

**Comment by goodwake** [comment]
can you send me the  anime.list file

**Comment by KevCui** [comment]
Hey @kraithus, could you run script with `-d` to enable debug mode? It will print out all necessary logs. If you'd like to share some logs, I will take a closer look. Thanks!

**Comment by lord8266** [comment]
@goodwake use the latest code, nice trick @KevCui

**Comment by kraithus** [comment]
> Hey @kraithus, could you run script with `-d` to enable debug mode? It will print out all necessary logs. If you'd like to share some logs, I will take a closer look. Thanks!

I see you resolved the issue, just in case, here is the log [log_animepahe-dl.txt](https://github.com/KevCui/animepahe-dl/files/13260691/log_animepahe-dl.txt) from before I pulled the recent changes where it is now working as expected. Thank you!

Command ran `./animepahe-dl.sh -d -a 'hxeros' -e 1  -t 30 -o jpn`

**Comment by kraithus** [comment]
> @goodwake @kraithus use the latest code, nice trick @KevCui

I just did, thank you, working as expected!

**Comment by KevCui** [comment]
Hey @kraithus, glad the last commit is working for you. I'm closing this issue. Cheers.
