### ISSUE TITLE
Episode names

### ISSUE THREAD

**Issue by ayan-akd** [KevCui/animepahe-dl#96]
Instead of just 1,2,3,4.... is it possible to auto-name the episodes like [Anime-name]-Epi-[epi-number]?

**Comment by KevCui** [comment]
Hey @ayan-akd, yes, it's possible. You can change this line https://github.com/KevCui/animepahe-dl/blob/dda1c965251ba98951a4f80c5f228e5290d13cae/animepahe-dl.sh#L339 to `v="$_SCRIPT_PATH/${_ANIME_NAME}/${_ANIME_NAME}-Epi-${num}.mp4"`. It should work.

**Comment by ayan-akd** [comment]
Thank you
