### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by marcusbake22** [KevCui/animepahe-dl#98]
i need help i keep trying git bash and it keeps saying parse error invalid numeric literal at line 1 column 10

**Comment by marcusbake22** [comment]
![Screenshot 2024-01-16 162038](https://github.com/KevCui/animepahe-dl/assets/156812295/fc1738a4-eeff-4051-a7e1-628a66014101)
pleae help me

**Comment by lord8266** [comment]
script is broken yet again

**Comment by lord8266** [comment]
Changing line 129 to 
`    _COOKIE="uuid=$u; __ddgid=; __ddgmark_=; __ddg2_=; __ddg1="` seems to make it work

**Comment by KevCui** [comment]
Hey @marcusbake22, latest commit #445a5d7 fix this issue. Give it a try.

Thanks @lord8266 for the hint!
